# Generated by Django 5.0.7 on 2025-01-22 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companies_created_by'),
        ('users', '0002_favourite_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.BooleanField(default=False, verbose_name='Координатор')),
                ('categories', models.ManyToManyField(related_name='category_list', to='companies.companies', verbose_name='Компании')),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Особые права',
                'verbose_name_plural': 'Особые права',
            },
        ),
    ]
