# Generated by Django 5.0.7 on 2025-01-14 01:41

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dezh_Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Дежурный рабочий')),
            ],
            options={
                'verbose_name': 'Дежурного исполнителя',
                'verbose_name_plural': 'Дежурные исполнители',
                'db_table': 'dezh_worker',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['role'], name='roles_role_8b02c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Status_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус заявки')),
                ('do', models.CharField(max_length=50, null=True, verbose_name='Действия')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статус заявок',
                'db_table': 'status_application',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['name'], name='status_appl_name_6ceb6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.cities')),
            ],
            options={
                'verbose_name': 'Улицу',
                'verbose_name_plural': 'Улицы',
                'db_table': 'street',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Номер дома')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companies')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.master')),
                ('worker', models.ManyToManyField(to='companies.worker')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.street')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'db_table': 'house',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ATS', models.PositiveIntegerField(default=0, verbose_name='Номер АТС')),
                ('sms', models.CharField(choices=[('FULL', 'полный'), ('ABBREVIATED', 'сокращенный'), ('EMPTY', 'пусто')], default='EMPTY', max_length=55)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'username',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='View_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Вид заявки')),
            ],
            options={
                'verbose_name': 'Вид заявки',
                'verbose_name_plural': 'Виды заявок',
                'db_table': 'view_application',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['name'], name='view_applic_name_f34571_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['name'], name='street_name_161986_idx'),
        ),
        migrations.AddIndex(
            model_name='usernames',
            index=models.Index(fields=['name'], name='username_name_b6298b_idx'),
        ),
    ]
