# Generated by Django 5.0.7 on 2024-12-17 06:34

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dezh_Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Дежурный рабочий')),
            ],
            options={
                'verbose_name': 'Дежурного исполнителя',
                'verbose_name_plural': 'Дежурные исполнители',
                'db_table': 'dezh_worker',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Мастера',
                'verbose_name_plural': 'Мастера',
                'db_table': 'master',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'city',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['name'], name='city_name_88111b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона 1')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('info', models.TextField(default='Не заполнено', verbose_name='Информация')),
                ('sms_master', models.BooleanField(default=False, verbose_name='Смс мастеру')),
                ('sms_worker', models.BooleanField(default=False, verbose_name='Смс исполнителю')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компанию',
                'verbose_name_plural': 'Компании',
                'db_table': 'company',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['role'], name='roles_role_8b02c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Status_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус заявки')),
                ('do', models.CharField(max_length=50, null=True, verbose_name='Действия')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статус заявок',
                'db_table': 'status_application',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['name'], name='status_appl_name_6ceb6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.city')),
            ],
            options={
                'verbose_name': 'Улицу',
                'verbose_name_plural': 'Улицы',
                'db_table': 'street',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Type_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Типы заявок',
                'db_table': 'type_application',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['name'], name='type_applic_name_6a2720_idx')],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Номер дома')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.company')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.master')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.street')),
                ('type_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.type_application')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'db_table': 'house',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ATS', models.PositiveIntegerField(default=0, verbose_name='Номер АТС')),
                ('sms', models.CharField(choices=[('FULL', 'полный'), ('ABBREVIATED', 'сокращенный'), ('EMPTY', 'пусто')], default='EMPTY', max_length=55)),
                ('company', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.company')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'username',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='View_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Вид заявки')),
            ],
            options={
                'verbose_name': 'Вид заявки',
                'verbose_name_plural': 'Виды заявок',
                'db_table': 'view_application',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['name'], name='view_applic_name_f34571_idx')],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Рабочий')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Адрес', to='handbook.house')),
                ('type_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.type_application')),
            ],
            options={
                'verbose_name': 'Исполнителя',
                'verbose_name_plural': 'Исполнители',
                'db_table': 'worker',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='house',
            name='SOI_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Осмотр_СОИ', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Акт', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='carpenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Плотники', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='cleaners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Уборщицы', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='deratization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Дератизация', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='disinfection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Дезинфекция', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='electrician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Электрика', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='electrician_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Акт_электрика', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='improvement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Благоустройство', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='intercom_ROST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Домофон_РОСТ', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='networks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Сети', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='passport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Паспортный', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='pest_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Дезинсекция', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='plumber_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Акт_сантехника', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='plumbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Сантехника', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='verification_of_meters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Поверка_счетчиков', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='wipers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Дворники', to='handbook.worker'),
        ),
        migrations.AddField(
            model_name='house',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.worker'),
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.master')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='handbook.worker')),
            ],
            options={
                'verbose_name': 'Сотрудника',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'workers',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['name'], name='street_name_161986_idx'),
        ),
        migrations.AddIndex(
            model_name='usernames',
            index=models.Index(fields=['name'], name='username_name_b6298b_idx'),
        ),
    ]
