# Generated by Django 5.0.7 on 2024-12-25 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('handbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('name',), 'verbose_name': 'Мастера', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AddField(
            model_name='worker',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Мастер', to='handbook.master'),
        ),
        migrations.AlterField(
            model_name='master',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Мастера', to='companies.companies'),
        ),
        migrations.AlterField(
            model_name='master',
            name='workers',
            field=models.ManyToManyField(related_name='Исполнители', to='handbook.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
