# Generated by Django 5.0.7 on 2024-12-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_alter_master_options_worker_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='workers',
            field=models.ManyToManyField(related_name='Workers', to='handbook.worker'),
        ),
    ]
