# Generated by Django 5.0.7 on 2025-01-21 05:59

import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Мастер')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=18, null=True, region=None, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Мастера',
                'verbose_name_plural': 'Мастера',
                'db_table': 'master',
                'ordering': ('name',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Type_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Типы заявок',
                'db_table': 'type_application',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Исполнитель')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=18, null=True, region=None, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Исполнителя',
                'verbose_name_plural': 'Исполнители',
                'db_table': 'worker',
                'ordering': ('id',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['name'], name='cities_name_a7bf2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('info', models.TextField(default='Не заполнено', verbose_name='Информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(choices=[(1, 'Включено'), (0, 'Отключено')], default=1, verbose_name='Статус')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Город', to='companies.cities')),
            ],
            options={
                'verbose_name': 'Компанию',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
                'ordering': ('id',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
