# Generated by Django 5.0.7 on 2024-12-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='sms_master',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='sms_worker',
        ),
        migrations.AddField(
            model_name='companies',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
