# Generated by Django 5.0.7 on 2025-01-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='members',
        ),
    ]
