# Generated by Django 5.0.7 on 2025-01-21 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companies',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Мастер', to='companies.master'),
        ),
        migrations.AddIndex(
            model_name='type_application',
            index=models.Index(fields=['name'], name='type_applic_name_6a2720_idx'),
        ),
        migrations.AddField(
            model_name='worker',
            name='type_of_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Специальность', to='companies.type_application'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companies',
            name='worker',
            field=models.ManyToManyField(to='companies.worker'),
        ),
    ]
