# Generated by Django 5.0.7 on 2024-12-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companies_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='status',
        ),
    ]
