# Generated by Django 5.0.7 on 2025-01-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_coordinator',
            field=models.BooleanField(default=False, verbose_name='Координатор'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_dispatcher',
            field=models.BooleanField(default=False, verbose_name='Диспетчер'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_duty_dispatcher',
            field=models.BooleanField(default=False, verbose_name='Дежурный диспетчер'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_duty_executor',
            field=models.BooleanField(default=False, verbose_name='Дежурный исполнитель'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_executor',
            field=models.BooleanField(default=False, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='Мастер'),
        ),
    ]
