# Generated by Django 5.0.7 on 2025-01-14 01:41

import datetime
import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('handbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('текущая', 'текущая'), ('плановая', 'плановая'), ('аварийная', 'аварийная'), ('дежурная', 'дежурная'), ('коммерческая', 'коммерческая')], default='текущая', max_length=12, verbose_name='Приоритет заявки')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2025, 1, 14, 8, 41, 14, 628210), verbose_name='Дата создания заявки')),
                ('flat', models.CharField(max_length=3, null=True, verbose_name='Квартира')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст заявки')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=18, null=True, region=None, verbose_name='Номер телефона')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО заявителя')),
                ('job_date', models.DateField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('ASSIGNED', 'Назначена'), ('COMPLETED', 'Выполнена'), ('CLOSED', 'Закрыта'), ('DELIVERED_TO_GP_TRSKK', 'Передано в ГП ЦРКК'), ('NO_POSSIBLE', 'Нет возможности выполнения'), ('FAILED', 'Провалена'), ('FOR_CONTRACTORS', 'Для подрядчиков'), ('DELIVERED_IN_KRASKOM', 'Передано в Краском'), ('DELIVERED_IN_RES', 'Передано в РЭС'), ('DELIVERED_IN_SB_RAS', 'Передано в СО РАН'), ('DELIVERED_IN_PTO', 'Передано в ПТО')], default='NEW', max_length=50, verbose_name='Статус заявки')),
                ('povtornaya', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Повторная')),
                ('comment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Комментарий')),
                ('call_record', models.FileField(blank=True, null=True, upload_to='call_record', verbose_name='Запись разговора')),
                ('voice_record', models.FileField(blank=True, null=True, upload_to='voice_message', verbose_name='Голосовые сообщения')),
                ('new_sms', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс жителю "Заявка принята"')),
                ('sms_master', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс мастеру')),
                ('sms_about_worker', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс назначение исполнителя')),
                ('sms_worker', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс исполнителю')),
                ('sms_complete', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс выполнение заявки')),
                ('sms_dezh_worker', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс дежурному исполнителю')),
                ('materials', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материалы')),
                ('files', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Прикрепленные файлы')),
                ('last_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения заявки')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.companies', verbose_name='Компания')),
                ('dezh_worker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.dezh_worker', verbose_name='Дежурный исполнитель')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.house', verbose_name='Дом')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.master', verbose_name='Мастер')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.street', verbose_name='Улица')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.type_application', verbose_name='Тип заявки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.view_application', verbose_name='Вид заявки')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.worker', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
                'db_table': 'applications',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['text'], name='application_text_743a82_idx')],
            },
            managers=[
                ('converted_to_complete', django.db.models.manager.Manager()),
            ],
        ),
    ]
