# Generated by Django 5.0.7 on 2024-12-17 06:34

import datetime
import django.db.models.deletion
import list_of_request.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2024, 12, 17, 13, 34, 15, 519869), verbose_name='Дата создания заявки')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата от')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата до')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='Время от')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='Время до')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('clock', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('flat', models.CharField(max_length=3, null=True, verbose_name='Квартира')),
                ('text', models.TextField(blank=True, max_length=255, null=True, verbose_name='Текст заявки')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, null=True, region=None, verbose_name='Номер телефона')),
                ('extension_phone', models.CharField(default='Не указан номер', max_length=50, verbose_name='Доп. телефон')),
                ('fio', models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО заявителя')),
                ('job_date', models.DateField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('application_status', models.CharField(default=[0], max_length=50, validators=[list_of_request.models.Articles.status_validator], verbose_name='Статус заявки')),
                ('povtornaya', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Повторная')),
                ('comment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Комментарий')),
                ('end_date', models.DateField(blank=True, max_length=50, null=True, verbose_name='Дата выполнения')),
                ('call_record', models.FileField(blank=True, null=True, upload_to='call_record', verbose_name='Запись разговора')),
                ('voice_record', models.FileField(blank=True, null=True, upload_to='voice_message', verbose_name='Голосовые сообщения')),
                ('record_status', models.CharField(choices=[('ACTIVE', 'активная'), ('ARCHIVE', 'архивная')], default='ACTIVE', max_length=55, verbose_name='Статус записи')),
                ('new_sms', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс жителю "Заявка принята"')),
                ('sms_master', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс мастеру')),
                ('sms_about_worker', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс назначение исполнителя')),
                ('sms_worker', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс исполнителю')),
                ('sms_complete', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс выполнение заявки')),
                ('sms_dezh_worker', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='смс дежурному исполнителю')),
                ('materials', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материалы')),
                ('files', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Прикрепленные файлы')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения заявки')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.company', verbose_name='Компания')),
                ('dezh_worker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.dezh_worker', verbose_name='Дежурный исполнитель')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.house', verbose_name='Дом')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.master', verbose_name='Мастер')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.street', verbose_name='Улица')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.type_application', verbose_name='Тип заявки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.view_application', verbose_name='Вид заявки')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.worker', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
                'db_table': 'applications',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['text'], name='application_text_743a82_idx')],
            },
        ),
    ]
