# Generated by Django 5.0.7 on 2024-12-25 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 13, 26, 14, 201399), verbose_name='Дата создания заявки'),
        ),
    ]
