# Generated by Django 5.0.7 on 2025-01-14 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 8, 44, 57, 881504), verbose_name='Дата создания заявки'),
        ),
    ]
