# Generated by Django 5.0.7 on 2024-12-17 06:55

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 13, 55, 19, 538291), verbose_name='Дата создания заявки'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=18, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
