# Generated by Django 5.0.7 on 2025-01-21 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0002_articles_user_alter_articles_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 13, 49, 16, 427431), verbose_name='Дата создания заявки'),
        ),
    ]
