# Generated by Django 5.0.7 on 2024-12-17 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0002_alter_articles_create_time_alter_articles_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='record_status',
        ),
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 14, 0, 39, 763567), verbose_name='Дата создания заявки'),
        ),
    ]
