# Generated by Django 5.0.7 on 2024-12-25 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0003_alter_articles_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 13, 52, 40, 451462), verbose_name='Дата создания заявки'),
        ),
    ]
