# Generated by Django 5.0.7 on 2025-01-21 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0003_alter_articles_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 14, 8, 6, 154001), verbose_name='Дата создания заявки'),
        ),
    ]
