# Generated by Django 5.0.7 on 2025-01-15 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0003_alter_articles_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 9, 25, 7, 531604), verbose_name='Дата создания заявки'),
        ),
    ]
