# Generated by Django 5.0.7 on 2024-12-26 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0005_alter_articles_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 11, 13, 23, 663202), verbose_name='Дата создания заявки'),
        ),
    ]
