# Generated by Django 5.0.7 on 2025-01-27 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0005_alter_articles_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='converted_to_complete',
        ),
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 15, 21, 49, 619782), verbose_name='Дата создания заявки'),
        ),
    ]
