# Generated by Django 5.0.7 on 2024-12-26 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_request', '0006_alter_articles_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 13, 52, 32, 717469), verbose_name='Дата создания заявки'),
        ),
    ]
